sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: PYURJ4XbDnoB7Lq+kAm84G0rjnh1K7M/mpWy0yzGA9/OtBD+MSwhA4pG+aWrZIslqNSVYJ222BfzLBCIH3zK8TsWWfJv7WygPJXWzDVUsbLcq9GJhpO3BDC1sSkj3fgsxKR2nUCsxCsoucLHxSCh+NpGzOLPuhbn2YY+bONEcFc=
