---
tags: [mobile]
projects: [spring-mobile]
---
:spring_boot_version: 1.2.2.RELEASE
:Component: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/stereotype/Component.html
:ComponentScan: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ComponentScan.html
:View: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/View.html
:DeviceHandlerMethodArgumentResolver: http://docs.spring.io/spring-mobile/docs/1.1.x/api/org/springframework/mobile/device/DeviceHandlerMethodArgumentResolver.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:DeviceResolverHandlerInterceptor: http://docs.spring.io/spring-mobile/docs/1.1.x/api/org/springframework/mobile/device/DeviceResolverHandlerInterceptor.html
:Device: http://docs.spring.io/spring-mobile/docs/1.1.x/api/org/springframework/mobile/device/Device.html
:DispatcherServlet: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:WebMvcConfigurerAdapter: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.html
:ViewResolver: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/ViewResolver.html
:ResponseBody: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:ThymeleafViewResolver: http://www.thymeleaf.org/apidocs/thymeleaf-spring3/1.0.1/org/thymeleaf/spring3/view/ThymeleafViewResolver.html
:LiteDeviceDelegatingViewResolver: http://docs.spring.io/spring-mobile/docs/1.1.x/api/org/springframework/mobile/device/view/LiteDeviceDelegatingViewResolver.html
:Controller: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/stereotype/Controller.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-serving-mobile-web-content

This guide walks you through the process of using Spring to serve different views to normal, mobile and tablet devices.

== What you'll build

You'll build a service that will accept HTTP GET requests at:

    http://localhost:8080/greeting

and respond with a web page displaying a greeting for a normal desktop browser:

    "Hello standard view!"

Mobile phone browsers will see:

    "Hello mobile view!"

and tablets:

    "Hello tablet view!"

== What you'll need

:java_version: 1.7
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


:jump_ahead: Create a configuration class
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]

By including the Spring Mobile dependency, Spring Boot configures a {DeviceResolverHandlerInterceptor}[`DeviceResolverHandlerInterceptor`] and {DeviceHandlerMethodArgumentResolver}[`DeviceHandlerMethodArgumentResolver`] automatically. {DeviceResolverHandlerInterceptor}[`DeviceResolverHandlerInterceptor`] examines the `User-Agent` header in the incoming request, and based on the header value, determines whether the request is coming from a desktop browser, a mobile browser, or a tablet browser. The {DeviceHandlerMethodArgumentResolver}[`DeviceHandlerMethodArgumentResolver`] allows Spring MVC to use the resolved {Device}[`Device`] object in a controller method.


[[initial]]
== Create a properties file

Use the following property to enable Spring Boot auto-configuration for alternative mobile and tablet views:

`src/main/resources/application.properties`
[source,java]
----
include::complete/src/main/resources/application.properties[]
----

Internally, {LiteDeviceDelegatingViewResolver}[`LiteDeviceDelegatingViewResolver`] makes use of the {Device}[`Device`] resolved by {DeviceResolverHandlerInterceptor}[`DeviceResolverHandlerInterceptor`] to determine whether to return normal, mobile, or tablet specific views for a request. In this case, {LiteDeviceDelegatingViewResolver}[`LiteDeviceDelegatingViewResolver`] is configured to delegate requests to {ThymeleafViewResolver}[`ThymeleafViewResolver`]. {ThymeleafViewResolver}[`ThymeleafViewResolver`] is a type of {ViewResolver}[`ViewResolver`], which is used by Spring to perform server-side rendering of HTML. Spring Boot defaults to `mobile/` and `tablet/` prefixes for the corresponding views, but alternate locations can be configured with additional properties.


== Create a web controller

In Spring's approach to building web sites, HTTP requests are handled by a controller. You can easily identify these requests by the {Controller}[`@Controller`] annotation. In the following example, the GreetingController handles GET requests for /greeting by returning the name of a {View}[`View`], in this case, "greeting". A {View}[`View`] is responsible for rendering the HTML content:

`src/main/java/hello/GreetingController.java`
[source,java]
----
include::complete/src/main/java/hello/GreetingController.java[]
----

The `@RequestMapping` annotation ensures that HTTP requests to `/greeting` are mapped to the `greeting()` method.

NOTE: The above example does not specify `GET` vs. `PUT`, `POST`, and so forth, because `@RequestMapping` maps all HTTP operations by default. Use `@RequestMapping(method=GET)` to narrow this mapping.

The implementation of the method body relies on a link:/understanding/view-templates[view technology], in this case http://www.thymeleaf.org/doc/html/Thymeleaf-Spring3.html[Thymeleaf], to perform server-side rendering of the HTML. Thymeleaf parses the `greeting.html` template below and renders the HTML.

`src/main/resources/templates/greeting.html`
[source,html]
----
include::complete/src/main/resources/templates/greeting.html[]
----

Note the location of the mobile and tablet versions of the greeting view. These are the default locations used by auto-configuration. Additional properties are available to specify alternate locations.

    └── src
        └── main
            └── resources
                └── templates
                    └── greeting.html
                    └── mobile
                        └── greeting.html
                    └── tablet
                        └── greeting.html

The html body differs slightly for each greeting. The tablet version includes the following:

    <p th:text="'Hello tablet view!'" />

Likewise the mobile version of the greeting view includes the following html:

    <p th:text="'Hello mobile view!'" />


== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated in the next section creates a _standalone application_. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. And along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

`@SpringBootApplication` is a convenience annotation that adds all of the following:
    
- `@Configuration` tags the class as a source of bean definitions for the application context.
- `@EnableAutoConfiguration` tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
- Normally you would add `@EnableWebMvc` for a Spring MVC app, but Spring Boot adds it automatically when it sees **spring-webmvc** on the classpath. This flags the application as a web application and activates key behaviors such as setting up a `DispatcherServlet`.
- `@ComponentScan` tells Spring to look for other components, configurations, and services in the the `hello` package, allowing it to find the `HelloController`.

The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an application. Did you notice that there wasn't a single line of XML? No **web.xml** file either. This web application is 100% pure Java and you didn't have to deal with configuring any plumbing or infrastructure.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


Logging output is displayed. The service should be up and running within a few seconds.


== Test the service

Now that the web site is running, visit http://localhost:8080/greeting, where you see:

    "Hello standard view!"

Using an iOS simulator or Android emulator you will see:

    "Hello mobile view!"

or

    "Hello tablet view!" 


== Summary

Congratulations! You have just developed a simple web page that detects the type of device being used by a client and serves different views for each device type.
